  - name: Calendar db init job config map
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: configmap_file_init_db.yml.j2
    when: WITH_CALENDAR_INIT

  - name: Calendar db init job config map
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      state: absent
      api_version: v1
      kind: ConfigMap
      name: calendar-db-init-file
    when: not WITH_CALENDAR_INIT

  - name: Calendar db init job
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: job_init_db.yml.j2
    when: WITH_CALENDAR_INIT

  - name: Calendar db init job
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      state: absent
      api_version: batch/v1
      kind: Job
      name: calendar-db-init-job
    when: not WITH_CALENDAR_INIT
