name: Run develop at the end of every day
on:
  schedule:    
    - cron: "*0 0 * * *"

  jobs:
	stale:
		runs-on: ubuntu-18.04
		steps:
			- uses: actions/checkout@v2

			- name: Build image
        run: make build
    
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: make push
    
      - name: Cleanup
        run: make clean
